baseURL = 'https://xm.sc.cn/'
languageCode = 'en-us'
title = 'Parafoil dynamics'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 2
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]