baseURL = 'https://xm.sc.cn/'
languageCode = 'en-us'
title = 'Parafoil Research Library'
theme = 'hugo-book'

# Book configuration
# disablePathToLower = false
#enableGitInfo = true

[params]
  gitsite = 'https://github.com/qchen-fdii-cardc/parafoil/'
  maxImgSize = 300

# Needed for mermaid/katex shortcodes
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'
  [markup.goldmark]
    [markup.goldmark.parser]
        [markup.goldmark.parser.attribute]
        block = true
        title = true

    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]